##############################################################################
# Chrome
##############################################################################

- name: "Install/update chrome packages"
  apt:
    pkg: "{{ chrome_packages }}"
    state: latest
  become: yes
