##############################################################################
# Git
##############################################################################

##############################################################################
# Configuration
##############################################################################

- name: "Git configuration to {{ ansible_env.HOME }}/.gitconfig"
  template:
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    src: gitconfig.j2
    force: no

##############################################################################
# Setup Git LFS Deb Repository
##############################################################################

- name: "Ensure {{ ansible_env.HOME }}/.git_extras exists and is accessible by {{ ansible_user_id }}."
  file:
    path: "{{ ansible_env.HOME }}/.git_extras"
    state: directory
    recurse: no
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: users
  become: yes

- name: Download git lfs support installer script from package cloud
  get_url:
    url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
    dest: "{{ ansible_env.HOME }}/.git_extras/git-lfs.sh"
    force: no  # don't download again if it is already there, even if changed
    mode: 0755
  register: git_lfs_installer_script

- name: Install git lfs support
  shell: "{{ ansible_env.HOME }}/.git_extras/git-lfs.sh"
  args:
    executable: /bin/bash
  when: git_lfs_installer_script.changed
  become: yes

