---

##############################################################################
# Preparatory Tasks (but no deb installs)
##############################################################################

- include: sysadmin.yaml
- include: language.yaml
- include: konsole.yaml
- include: snorriheim.yaml
- include: xelatex.yaml
- include: workspaces.yaml

##############################################################################
