##############################################################################
# Snorriheim
##############################################################################
#
# Requirements:
#
#  - script: groot-ansible-bootstrap has added the snorriheim ppa
#  - role  : git
#
##############################################################################
# Preparation
##############################################################################

- name: "clone groot_eclipse_preferences"
  git:
    repo: https://github.com/stonier/groot_eclipse_preferences.git
    dest: /opt/groot-eclipse-preferences
    version: devel
    update: no

##############################################################################
# Debs
##############################################################################

- name: "install/update snorriheim packages"
  apt:
    pkg: "{{ snorriheim_packages }}"
    state: latest
  become: yes
