##############################################################################
# Tasks
##############################################################################

#############################################################################
# PPA
#############################################################################

- name: add snorriheim ppa
  apt_repository:
    repo: "{{ snorriheim_ppa_uri }}"
    state: present
    filename: snorriheim
    update_cache: yes
  become: yes

##############################################################################
# Debs
##############################################################################

- name: "install/update snorriheim packages"
  apt:
    pkg: "{{ snorriheim_packages }}"
    state: latest
  become: yes


##############################################################################
