#################################################################################################
# Snorriheim
#################################################################################################

snorriheim_ppa_uri: "ppa:d-stonier/snorriheim"

# all except groot-eclipse-neon-amd64 - it's super slow
snorriheim_packages  : [groot-icons, groot-wallpapers]
#snorriheim_packages  : [groot-eclipse-preferences, groot-icons,
#                        groot-mediterranean-themes, groot-wallpapers, python-ckx-tools,
#                        python-groot-tools, python-vci, ttygif
#                        ]
