#
# Playbook to ensure ros is installed and up to date. This includes:
#
# - the ros repository
# - ros-<rosdistro>-base
# - rosdep
# - any other ros packages the user may have installed
#
---
- name: ROS Installation and Update
  hosts:
    - localhost

  vars:
  # Public Variables
  - ros_release: kinetic

  roles:
  - role: ros
    ros_release: "{{ ros_release }}"
