#
# Playbook to ensure ros is installed and up to date. This includes:
#
# - the ros repository
# - ros-<rosdistro>-base
# - rosdep
# - any other ros packages the user may have installed
#
---
- name: Testies
  hosts:
    - localhost

  roles:
  - role: testies

  pre_tasks:
  - name: Test the vci module
    vci:
      key: catkin
    register: result
  - debug: var=result
