#################################################################################################
# Defaults
#################################################################################################

kubuntu_packages     : [kubuntu-full]
anti_kubuntu_packages: [unity-scope-gdrive, account-plugin-google account-plugin-facebook]
