---
dependencies: []

galaxy_info:
  author: Daniel Stonier
  description: ROS 2 installation for Ubuntu
  company: Snorriheim
  license: BSD
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  categories:
    - development
    - system
