#################################################################################################
# Defaults
#################################################################################################

powerline_packages : [fonts-powerline, powerline, python3-powerline-gitstatus]
