#################################################################################################
# Defaults
#################################################################################################

powerline_packages : [fonts-powerline, powerline]
