#################################################################################################
# Defaults
#################################################################################################

powerline_packages : [fonts-powerline, powerline, python-powerline-gitstatus]
