---
#############################################################################
# Setting Up
#############################################################################

- name: Add ros repository apt-key
  apt_key:
    url: "{{ ros_apt_key }}"
    state: present
  become: yes

- name: Add ros repository
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
    filename: ros-latest
  become: yes

#############################################################################
# Apt Update
#############################################################################

# In case we didn't add the ros repository in the previous step
- name: Apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

#############################################################################
# Ros Core
#############################################################################

- name: "Update package 'ros-{{ ros_release }}-{{ ros_package }}'"
  apt:
    pkg: "ros-{{ ros_release }}-{{ ros_package }}"
    state: latest
  become: yes

#############################################################################
# Ros Update
#############################################################################

- name: Update ros python packages
  apt:
    pkg: "{{ item }}"
    only_upgrade: yes
    state: latest
  with_items:
    - python-rosdep
    - python-bloom
    - python-wstool
    - python-catkin-pkg
  become: yes

# Bastard doesn't properly return changed when nothing is installed/upgraded
# Do our own changed_when on the result
- name: Update all ros-{{ ros_release }} packages
  apt:
    pkg: ros-{{ ros_release }}-*
    only_upgrade: yes
    state: latest
  become: yes
  register: update_ros_packages_result
  changed_when: "'0 upgraded, 0 newly installed' not in update_ros_packages_result.stdout"


#############################################################################
# Rosdep Update
#############################################################################

- name: RosDep init
  shell: "rosdep init"
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
  become: yes

# No way of having a reliable changed or not here unless we go to extremes
# in checking file sizes and such
- name: "Rosdep update (warning: changes undetectable)"
  shell: "rosdep update"
  register: rosdep_result
  changed_when: False
