#############################################################################
# Setup
#############################################################################

- name: install/update packages needed for ros2 installation
  apt:
    pkg: "{{ installation_packages }}"
    state: latest
  register: update_ros2_installation_packages_result
  become: yes

- name: add ros2 apt-key
  apt_key:
    url: "{{ ros2_key_server }}"
    state: present
  become: yes

- name: add ros2 repository
  apt_repository:
    repo: "deb [arch=amd64,arm64] {{ ros2_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
    filename: ros2-latest
    update_cache: yes
  become: yes

#############################################################################
# Apt Packages
#############################################################################

- name: install/update ros2 development packages
  apt:
    pkg: "{{ development_packages }}"
    state: latest
  register: update_ros2_python_packages_result
  become: yes

- name: "install/update 'ros-{{ ros2_distro }}-desktop'"
  apt:
    pkg: "ros-{{ ros2_distro }}-ros-base"
    state: latest
  become: yes

# Not yet available
#- name: "install/update 'ros-{{ ros2_distro }}-ros-desktop'"
#  apt:
#    pkg: "ros-{{ ros2_distro }}-ros-desktop"
#    state: latest
#  become: yes

#############################################################################
# Update
#############################################################################

# Check in that it now informs properly when something is upgraded.
# Previously (trusty, xenial) we used a register hook with a
# changed_when conditional to check for the resulting phrase on the
# stdout of the result. The apt module no longer seems pass on stdout
# to do our own checking in ansible 2.5 though.
- name: update all {{ ros2_distro }} packages
  apt:
    pkg: ros-{{ ros2_distro }}-*
    only_upgrade: yes
    state: latest
  become: yes

#############################################################################
# Rosdep Update
#############################################################################

- name: rosdep init
  shell: "rosdep init"
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
  become: yes

# No way of having a reliable changed or not here unless we go to extremes
# in checking file sizes and such. Run with -v to get registered result output
- name: "rosdep update (warning: changes undetectable)"
  shell: "rosdep update"
  register: rosdep_result
  changed_when: False
