#############################################################################
# Apt Repositories
#############################################################################

- name: add ros2 apt-key
  apt_key:
    url: "{{ ros2_key_server }}"
    state: present
  become: yes

- name: add ros2 repository
  apt_repository:
    repo: "deb [arch=amd64,arm64] {{ ros2_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
    filename: ros2
    update_cache: yes
  become: yes

#############################################################################
# Apt Packages
#############################################################################

- name: "update package 'ros-{{ ros2_distro }}-ros-base'"
  apt:
    pkg: "ros-{{ ros2_distro }}-ros-base"
    state: latest
  become: yes

#- name: "update package 'ros-{{ ros2_distro }}-ros-desktop'"
#  apt:
#    pkg: "ros-{{ ros2_distro }}-ros-desktop"
#    state: latest
#  become: yes

#############################################################################
# Update
#############################################################################

# Check in that it now informs properly when something is upgraded.
# Previously (trusty, xenial) we used a register hook with a
# changed_when conditional to check for the resulting phrase on the
# stdout of the result. The apt module no longer seems pass on stdout
# to do our own checking in ansible 2.5 though.
- name: update all {{ ros2_distro }} packages
  apt:
    pkg: ros-{{ ros2_distro }}-*
    only_upgrade: yes
    state: latest
  become: yes
