#############################################################################
# Apt Repositories
#############################################################################

- name: add ros/ros2 repository apt-key
  apt_key:
    keyserver: "{{ ros_key_server }}"
    id: "{{ ros_key_id }}"
    state: present
  become: yes

- name: add ros/ros2 repository
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
    filename: ros
    update_cache: yes
  become: yes

#############################################################################
# Apt Packages
#############################################################################

- name: "install/update core packages"
  apt:
    pkg: "{{ core_packages }}"
    state: latest
  become: yes

- name: "install/update build packages"
  apt:
    pkg: "{{ build_packages }}"
    state: latest
  become: yes

- name: "install/update testing packages"
  apt:
    pkg: "{{ testing_packages }}"
    state: latest
  become: yes

- name: "install/update fastrps packages"
  apt:
    pkg: "{{ fastrtps_packages }}"
    state: latest
  become: yes

