galaxy_info:
  author: Daniel Stonier
  description: Core setup and package installation on ubuntu for a development environment
  company: Snorriheim
  license: BSD
  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
    - xenial
