galaxy_info:
  author: Daniel Stonier
  description: VSCode for Ubuntu
  company: Snorriheim
  license: BSD
  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal

#dependencies:
#  - role: stonier.ansible
