##############################################################################
# Git Core Debs
##############################################################################

- name: "install/update git packages"
  apt:
    pkg: "{{ git_packages }}"
    state: latest
  become: yes

##############################################################################
# Configuration
##############################################################################

- name: "configuration to {{ ansible_env.HOME }}/.gitconfig"
  template:
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    src: gitconfig.j2
    force: no
