##############################################################################
# Git Core Debs
##############################################################################

- name: "install/update git packages"
  apt:
    pkg: "{{ git_packages }}"
    state: latest
  become: yes

##############################################################################
# Git LFS
##############################################################################

- name: "ensure {{ ansible_env.HOME }}/.git_extras exists and is accessible by {{ ansible_user_id }}"
  file:
    path: "{{ ansible_env.HOME }}/.git_extras"
    state: directory
    recurse: no
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: users

- name: download git lfs support installer script from package cloud
  get_url:
    url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
    dest: "{{ ansible_env.HOME }}/.git_extras/git-lfs.sh"
    force: no  # don't download again if it is already there, even if changed
    mode: 0755
  register: git_lfs_installer_script

- name: add git lfs repository
  shell: "{{ ansible_env.HOME }}/.git_extras/git-lfs.sh"
  args:
    executable: /bin/bash
  become: yes
  when: git_lfs_installer_script.changed

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 0
  become: yes
  when: git_lfs_installer_script.changed

##############################################################################
# Configuration
##############################################################################

- name: "configuration to {{ ansible_env.HOME }}/.gitconfig"
  template:
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    src: gitconfig.j2
    force: no
