#################################################################################################
# Kubuntu
#################################################################################################

kubuntu_packages     : [kubuntu-full]
anti_kubuntu_packages: [unity-scope-gdrive, account-plugin-google account-plugin-facebook]

#################################################################################################
# System Debs
#################################################################################################

language_packages    : [language-selector-gnome]

#################################################################################################
# Various
#################################################################################################

gpg_packages         : [gnupg, gnupg2]

#################################################################################################
# Snorriheim
#################################################################################################

snorriheim_packages  : [groot-eclipse-neon-amd64, groot-eclipse-preferences, groot-icons,
                        groot-mediterranean-themes, groot-wallpapers, python-ckx-tools,
                        python-groot-tools, python-vcs-extras
                        ]

