---
dependencies: []

galaxy_info:
  author: Daniel Stonier
  description: System76 driver installation and update.
  company: Snorriheim
  license: BSD
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - bionic
  categories:
    - development
    - system
