---
dependencies: []

galaxy_info:
  author: stonier
  description: Robot Operating System (ROS) installation for Linux.
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  categories:
    - development
    - system
