##############################################################################
# Docker
##############################################################################

- name: "install prereq debs"
  apt:
    pkg: "{{ prereq_packages }}"
    state: latest
  become: yes

- name: docker hub apt key
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present
  become: yes

- name: docker hub apt repository
  apt_repository:
    repo: "deb {{ docker_apt_uri }} {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: yes

- name: "docker engine debs"
  apt:
    pkg: "{{ docker_packages }}"
    state: latest
  become: yes

# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#docker
- name: "nvidia container toolkit - apt repo"
  shell: "distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -fsSL {{ nvidia_gpg_key }} | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/experimental/$distribution/libnvidia-container.list | \
         sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
         tee /etc/apt/sources.list.d/nvidia-container-toolkit.list"
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: yes

- name: "nvidia container toolkit - deb"
  apt:
    pkg: "{{ nvidia_packages }}"
    state: latest
    update_cache: true
  become: yes

- name: "nvidia container toolkit - configure"
  shell: "nvidia-ctk runtime configure --runtime=docker"
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: yes

- name: "restart docker"
  shell: "systemctl restart docker"
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: yes
