##############################################################################
# Snorriheim
##############################################################################
#
# Requirements:
#
#  - debs: groot-eclipse installed manually from snorriheim ppa
#
##############################################################################
# Eclipse
##############################################################################

- name: "eclipse script to /usr/local/bin/eclipse"
  template:
    dest: "/usr/local/bin/eclipse"
    src: eclipse.j2
    force: no
    owner: "{{ ansible_user_id }}"
    group: users
    mode: 0755
  become: yes  # just in case
