##############################################################################
# Language
##############################################################################
#
# Requirements:
#
#  - role  : ubuntu
#
##############################################################################
# Debs
##############################################################################

- name: "Install/update language packages"
  apt:
    pkg: "{{ language_packages }}"
    state: latest
  become: yes

##############################################################################
# Configuration - move out to a separate yaml later
##############################################################################

# This hopefully will save having to go in and manually click things in the
# last lanuage setup step
- name: "english/korean input configuration to {{ ansible_env.HOME }}/.config/fcitx/config"
  template:
    dest: "{{ ansible_env.HOME }}/.config/fcitx/config"
    src: fcitx.config.j2
    force: no
    mode: 0600
