##############################################################################
# Snorriheim
##############################################################################
#
# Requirements:
#
#  - script: groot-ansible-bootstrap has added the snorriheim ppa
#
# TODO: check if adding the ppa here doesn't hurt
#

#############################################################################
# PPA
#############################################################################

- name: add system76 ppa
  apt_repository:
    repo: "{{ snorriheim_ppa_uri }}"
    state: present
    filename: system76
    update_cache: yes
  become: yes

##############################################################################
# Debs
##############################################################################

- name: "install/update snorriheim packages"
  apt:
    pkg: "{{ snorriheim_packages }}"
    state: latest
  become: yes
