##############################################################################
# Snorriheim
##############################################################################
#
# Requirements:
#
#  - script: groot-ansible-bootstrap has added the snorriheim ppa
#
##############################################################################
# Debs
##############################################################################

- name: "install/update snorriheim packages"
  apt:
    pkg: "{{ snorriheim_packages }}"
    state: latest
  become: yes
