##############################################################################
# XELatex
#
# Requirements:
#  - role  : ubuntu (installs the xelatex debs)
#  - role  : git
#
##############################################################################

- name: "clone texmf -> {{ ansible_env.HOME }}/texmf"
  git:
    repo: https://github.com/stonier/texmf.git
    dest: "{{ ansible_env.HOME }}/texmf"
    version: devel
    update: yes
  register: texmf_clone

- name: "update user's texmf instance"
  shell: "texhash {{ ansible_env.HOME }}/texmf"
  args:
    executable: /bin/bash
  when: texmf_clone.changed

