#!/usr/bin/env bash

###########################
# Colours
###########################

BOLD="\e[1m"

CYAN="\e[36m"
GREEN="\e[32m"
RED="\e[31m"
YELLOW="\e[33m"

RESET="\e[0m"

###########################
# Functions
###########################

show_help ()
{
  echo ""
  echo "Bootstraps a pc system for a minimal setup to gain"
  echo "access to the snorriheim ppa. It will ask you for"
  echo "sudo permissions to run."
  echo ""
  echo "    Usage:"
  echo "        groot-ansible-bootstrap"
  echo ""
  echo "    Options:"
  echo "        --help            : this help message"
  exit 0
}

pretty_print ()
{
  echo -e "${GREEN}${1}${RESET}"
}

pretty_error ()
{
  echo -e "${RED}${1}${RESET}"
}

pretty_header ()
{
  echo -e "${BOLD}${1}${RESET}"
}

install_package ()
{
  PACKAGE_NAME=$1
  sudo apt-get -q -y install ${PACKAGE_NAME} > /dev/null
  if [ $? -ne 0 ]; then
    pretty_error "  ${PACKAGE_NAME}............failed"
    exit 0
  fi
  pretty_print "  ${PACKAGE_NAME}............ok"
}

# list_include_item "10 11 12" "2"
function list_include_item {
  local list="$1"
  local item="$2"
  if [[ $list =~ (^|[[:space:]])"$item"($|[[:space:]]) ]] ; then
    # yes, list include item
    result=0
  else
    result=1
  fi
  return $result
}

added_user()
{
  local stdout=$1
  if [[ $stdout == *"already a member"* ]]
  then
    echo "ok"
  else
    echo "added"
  fi
}

###########################
# Command Line
###########################

for i in "$@"
do
case $i in
    --help)
    SHOW_HELP=1
    shift
    ;;
    *)
       # pass through
    ;;
esac
done

###########################
# Aborts
###########################

if [ ! -z "$SHOW_HELP" ]; then
  show_help
  exit 0
fi

###########################
# Inside a VirtualEnv?
###########################

[[ "$VIRTUAL_ENV" == "" ]]; INVENV=$?

###########################
# Execute!
###########################

# actually, this is ubuntu only, but we don't support
# anything else yet.
. /etc/lsb-release

echo ""
pretty_header "Ubuntu Release Details"
pretty_print "  Release: ${DISTRIB_RELEASE}"
pretty_print "  Codename: ${DISTRIB_CODENAME}"
echo ""

pretty_header "Repositories"
if `list_include_item "trusty xenial" "${DISTRIB_CODENAME}"`; then
  # stuck with having to use a future ansible, drop this need asap if we can
  # as it is likely to cause us integration headaches with modules needing non
  # system supported dependencies
  pretty_print "  ansible........................ppa:ansible/ansible"
  if [ ! -f /etc/apt/sources.list.d/ansible-ansible-trusty.list ]; then
    sudo apt-add-repository --yes ppa:ansible/ansible
  fi
else
  pretty_print "  ansible........................system"
fi

if [ "$INVENV" -eq "0" ]; then
  pretty_print "  python-groot-ansible...........d-stonier/snorriheim"
  sudo apt-add-repository --yes ppa:d-stonier/snorriheim
else
  pretty_print "  python-groot-ansible...........virtualenv"
fi
echo ""

pretty_header "Apt-Get Update"
sudo apt-get update > /dev/null 2>&1
if [ $? -ne 0 ]; then
  pretty_error "  update.........................failed"
  exit 0
fi
pretty_print "  update.........................ok"
echo ""

pretty_header "Installing"
install_package ansible
if [ "$INVENV" -eq "0" ]; then
  install_package python-groot-ansible;
fi
echo ""

pretty_header "Groups"
sudo groupadd dialout 2>/dev/null
sudo groupadd --system docker 2>/dev/null
sudo groupadd users 2>/dev/null

dialout_added=$( added_user "`sudo adduser ${USER} dialout`")
pretty_print "  dialout........................$dialout_added"
docker_added=$( added_user "`sudo adduser ${USER} docker`")
pretty_print "  docker.........................$docker_added"
users_added=$( added_user "`sudo adduser ${USER} users`")
pretty_print "  users..........................$users_added"
echo ""

pretty_header "Summary"

echo -e "${GREEN}  If user groups changed, log out and log in again to utilise the changes.${RESET}"
echo ""
echo -e "${CYAN}  To continue setting up your environment, run ${RESET}${YELLOW}'groot-ansible --help'${RESET}${CYAN}.${RESET}"
echo ""
