#################################################################################################
# Defaults
#################################################################################################

git_packages : [vim, git]
