#################################################################################################
# Defaults
#################################################################################################

git_packages : [git]
