##############################################################################
# Git
##############################################################################

- name: "Install/update git packages"
  apt:
    pkg: "{{ git_packages }}"
    state: latest
  become: yes
