##############################################################################
# Git
##############################################################################

- name: "Git configuration to {{ ansible_env.HOME }/.gitconfig"
  template:
    dest: "{{ ansible_env.HOME }/.gitconfig"
    src: gitconfig.j2
    force: no
  tags: preparation

- name: "Git related packages"
  apt:
    pkg: "{{ git_packages }}"
    state: latest
  become: yes
  tags: apt_install
