#################################################################################################
# GPG
#################################################################################################

- name: Create ~/.gnupg directory
  file:
    state: directory
    mode: 0700
    path: ~/.gnupg
