##############################################################################
# Language
##############################################################################
#
# Requirements:
#
#  - task  : system-debs.yaml
#
##############################################################################
# Debs
##############################################################################

- name: "Install/update language packages"
  apt:
    pkg: "{{ language_packages }}"
    state: latest
  become: yes

##############################################################################
# Configuration - move out to a separate yaml later
##############################################################################
#
# could probably do something about fctix configuration file:
#
#    ~/.config/fcitx/config
#