##############################################################################
# Snorriheim
##############################################################################
#
# Requirements:
#
#  - script: groot-ansible-bootstrap has added the snorriheim ppa
#  - task  : git.yaml
#
##############################################################################
# Preparation
##############################################################################

- name: "Ensure /opt/snorriheim exists and is accessible by {{ ansible_user_id }}."
  file:
    path: "/opt/snorriheim"
    state: directory
    recurse: no
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: users
  become: yes

- name: "Clone groot_eclipse_preferences"
  git:
    repo: https://github.com/stonier/groot_eclipse_preferences.git
    dest: /opt/snorriheim/eclipse-preferences
    version: devel
    update: no

##############################################################################
# Debs
##############################################################################

- name: "Install/update snorriheim packages"
  apt:
    pkg: "{{ snorriheim_packages }}"
    state: latest
  become: yes
