##############################################################################
# Basic Sysadmin
##############################################################################

# Add to the users group - do it from groot-ansible-bootstrap instead since
# the changes can't go into effect till a reboot
#- user:
#    name: "{{ ansible_user_id }}"
#    groups: users,dialout,docker
#    append: yes

- name: "Ensure /usr/local/bin is accessible by {{ ansible_user_id }}."
  file:
    path: "/usr/local/bin"
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: users
  become: yes

- name: "Ensure /usr/local/lib is accessible by {{ ansible_user_id }}."
  file:
    path: "/usr/local/lib"
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: users
  become: yes
